name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install && npm install --prefix client && npm install --prefix server
      - name: Lint client
        run: npm run lint --prefix client
      - name: Test client
        run: npm test --prefix client
      - name: Test server
        run: npm test --prefix server
        env:
          TEST_MONGODB_URI: mongodb://localhost:27017/testdb
          SECRET: testsecret
      - name: Build
        run: npm run build
